# Generated by Django 4.1.7 on 2023-09-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_man', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('product_cost', models.IntegerField()),
                ('realise_date', models.DateTimeField()),
                ('img', models.ImageField(upload_to='images')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.manufact')),
            ],
        ),
    ]
